parameters:
    domis86_translator.translator.class: Domis86\TranslatorBundle\Translation\Translator
    domis86_translator.controller.translator_controller.class: Domis86\TranslatorBundle\Controller\TranslatorController
    domis86_translator.data_collector.class: Domis86\TranslatorBundle\DataCollector\TranslatorDataCollector

services:

# public

    domis86_translator.translator:
        class: '%domis86_translator.translator.class%'
        arguments: [@domis86_translator.message_manager, @translator.selector, %domis86_translator.ignored_domains%]

    domis86_translator.controller.translator_controller:
        class: '%domis86_translator.controller.translator_controller.class%'
        arguments: [@templating, @domis86_translator.web_debug_dialog, %domis86_translator.config%, @translator, @translation.writer]

# private

    domis86_translator.message_manager:
        public: false
        class: Domis86\TranslatorBundle\Translation\MessageManager
        arguments:
            - @domis86_translator.storage
            - @domis86_translator.cache_manager
            - @domis86_translator.message_verifier

    domis86_translator.web_debug_dialog:
        public: false
        class: Domis86\TranslatorBundle\Translation\WebDebugDialog
        arguments: [@domis86_translator.storage, @domis86_translator.cache_manager, @domis86_translator.message_verifier, %domis86_translator.managed_locales%]

    domis86_translator.message_verifier:
        public: false
        class: Domis86\TranslatorBundle\Translation\NamingVerifier
        arguments:
            - %domis86_translator.managed_locales%

    domis86_translator.storage:
        public: false
        class: Domis86\TranslatorBundle\Storage\Storage
        arguments: [@doctrine.orm.entity_manager]

    domis86_translator.cache_manager:
        public: false
        class: Domis86\TranslatorBundle\Translation\CacheManager
        arguments:
            - %kernel.cache_dir%/domis86translator
            - %kernel.debug%


# listeners - tags set in Domis86\TranslatorBundle\DependencyInjection\Extension

    domis86_translator.controller_listener:
        public: false
        class: Domis86\TranslatorBundle\EventListener\TranslatorControllerListener
        arguments: [@domis86_translator.message_manager, @translator, %domis86_translator.whitelisted_controllers_regexes%, %domis86_translator.ignored_controllers_regexes%]
    domis86_translator.response_listener:
        public: false
        class: Domis86\TranslatorBundle\EventListener\TranslatorResponseListener
        arguments: [@domis86_translator.message_manager, @templating, %domis86_translator.config%, @translator]
        scope: request
    domis86_translator.command_listener:
        public: false
        class: Domis86\TranslatorBundle\EventListener\TranslatorConsoleListener
        arguments: [@domis86_translator.message_manager, @translator, %domis86_translator.whitelisted_controllers_regexes%, %domis86_translator.ignored_controllers_regexes%]
